import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  ManyToOne,
  OneToMany,
  JoinColumn,
} from 'typeorm';
import { User } from './user.entity';
import { Tenant } from './tenant.entity';

/**
 * Conversation Entity
 *
 * Represents a chat conversation in the AI SaaS application. Each conversation
 * belongs to a specific user within a tenant and contains multiple messages.
 * Supports archiving, custom metadata, and tracks creation/update timestamps.
 * Used for organizing chat interactions and maintaining conversation history.
 */
@Entity('conversations')
export class Conversation {
  /** Unique identifier for the conversation (UUID) */
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /** ID of the user who owns this conversation */
  @Column({ name: 'user_id', type: 'uuid' })
  userId: string;

  /** ID of the tenant this conversation belongs to (multi-tenancy support) */
  @Column({ name: 'tenant_id', type: 'uuid' })
  tenantId: string;

  /** Optional title for the conversation (user-defined or auto-generated) */
  @Column({ length: 500, nullable: true })
  title: string;

  /** AI model used for this conversation (e.g., 'claude-3-5-sonnet-20241022') */
  @Column({ length: 100, default: 'claude-3-5-sonnet-20241022' })
  model: string;

  /** Flag indicating if the conversation has been archived by the user */
  @Column({ name: 'is_archived', default: false })
  isArchived: boolean;

  /** Flexible JSON metadata storage for conversation-specific settings or data */
  @Column({ type: 'jsonb', default: {} })
  metadata: Record<string, any>;

  /** Timestamp when the conversation was created */
  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt: Date;

  /** Timestamp when the conversation was last updated (auto-updated on changes) */
  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt: Date;

  // Relations

  /** Many-to-one relationship with User (conversation belongs to one user) */
  @ManyToOne(() => User, (user) => user.conversations, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'user_id' })
  user: User;

  /** Many-to-one relationship with Tenant (conversation belongs to one tenant) */
  @ManyToOne(() => Tenant, (tenant) => tenant.conversations, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'tenant_id' })
  tenant: Tenant;

  /** One-to-many relationship with Message (conversation has many messages) */
  @OneToMany(() => Message, (message) => message.conversation)
  messages: Message[];
}

/**
 * Message Role Enum
 *
 * Defines the possible roles for messages in a conversation.
 * Used to distinguish between user input, AI responses, and system messages.
 */
export enum MessageRole {
  /** Message sent by the user */
  USER = 'user',

  /** Response generated by the AI assistant */
  ASSISTANT = 'assistant',

  /** System-generated message (instructions, context, etc.) */
  SYSTEM = 'system',
}

/**
 * Message Entity
 *
 * Represents individual messages within a conversation. Each message has a role
 * (user, assistant, or system), content, and optional token count for billing.
 * Messages are ordered chronologically and linked to their parent conversation.
 */
@Entity('messages')
export class Message {
  /** Unique identifier for the message (UUID) */
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /** ID of the conversation this message belongs to */
  @Column({ name: 'conversation_id', type: 'uuid' })
  conversationId: string;

  /** Role of the message sender (user, assistant, or system) */
  @Column({
    type: 'enum',
    enum: MessageRole,
  })
  role: MessageRole;

  /** The actual content/text of the message */
  @Column({ type: 'text' })
  content: string;

  /** Number of tokens consumed by this message (used for billing/quota tracking) */
  @Column({ type: 'int', nullable: true })
  tokens: number | null;

  /** Flexible JSON metadata storage for message-specific data (e.g., model settings) */
  @Column({ type: 'jsonb', default: {} })
  metadata: Record<string, any>;

  /** Timestamp when the message was created */
  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt: Date;

  // Relations

  /** Many-to-one relationship with Conversation (message belongs to one conversation) */
  @ManyToOne(() => Conversation, (conversation) => conversation.messages, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'conversation_id' })
  conversation: Conversation;
}
